version: '3.8'

services:
  vocab-importer:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
